SCMS_VENUS: com.nordicsemi.venusAlpha01a.PacketParser Class Reference
com.nordicsemi.venusAlpha01a.PacketParser Class Reference
Public Member Functions
PacketParser ()
void ParseOnePacket (byte [] packet_raw_data)
전달 받은 압력 값을 구분하고 해당 값들을 변수에 Setting
Static Public Member Functions
static byte getSensorDataByCoord (int nRowIndex, int nColIndex)
static boolean isPostureValid_Row1 ()
static float getCOM_x_Row1 ()
static float getCOC_left_Row1 ()
static float getCOC_right_Row1 ()
static boolean isPacketCompleted ()
static byte getBatteryLevel ()
static byte [] getDataMainBoard ()
static byte [] getDataShieldBoard ()
Static Public Attributes
static byte m_BatteryLevel = 0
static byte def_CELL_COUNT_ROW0 = 6
static byte def_CELL_COUNT_ROW1 = 15
static byte def_CELL_COUNT_ROW2 = 10
static byte [] nChairVal_Row0 = new byte [def_CELL_COUNT_ROW0]
static byte [] nChairVal_Row1 = new byte [def_CELL_COUNT_ROW1]
static byte [] nChairVal_Row2 = new byte [def_CELL_COUNT_ROW2]
static final byte [] adcValue_M = new byte[20]
static final byte [] adcValue_S = new byte[20]
static boolean m_isPacketCompleted = false
static String textHexaMain = " "
static String textHexaShield = " "
Detailed Description
Created by sehjin12-pc on 2016-12-11.
압력세서로부터 전달 받은 데이터를 처리하여 직관적인 값으로 변환하고 사용할 변수에 Setting
Author
Marveldex
Date
2017-03-17
Version
0.0.1
list1
list2
Definition at line 21 of file PacketParser.java.
Constructor & Destructor Documentation
PacketParser()
com.nordicsemi.venusAlpha01a.PacketParser.PacketParser ()
Definition at line 42 of file PacketParser.java.
Member Function Documentation
getBatteryLevel()
static byte com.nordicsemi.venusAlpha01a.PacketParser.getBatteryLevel () static
Definition at line 249 of file PacketParser.java.
References com.nordicsemi.venusAlpha01a.PacketParser.m_BatteryLevel.
Referenced by com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
getCOC_left_Row1()
static float com.nordicsemi.venusAlpha01a.PacketParser.getCOC_left_Row1 () static
Definition at line 213 of file PacketParser.java.
References com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW1.
Referenced by com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
getCOC_right_Row1()
static float com.nordicsemi.venusAlpha01a.PacketParser.getCOC_right_Row1 () static
Definition at line 229 of file PacketParser.java.
Referenced by com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
getCOM_x_Row1()
static float com.nordicsemi.venusAlpha01a.PacketParser.getCOM_x_Row1 () static
Parameters
Definition at line 172 of file PacketParser.java.
References com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW1.
Referenced by com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
getDataMainBoard()
static byte [] com.nordicsemi.venusAlpha01a.PacketParser.getDataMainBoard () static
Definition at line 253 of file PacketParser.java.
References com.nordicsemi.venusAlpha01a.PacketParser.adcValue_M.
getDataShieldBoard()
static byte [] com.nordicsemi.venusAlpha01a.PacketParser.getDataShieldBoard () static
Definition at line 257 of file PacketParser.java.
References com.nordicsemi.venusAlpha01a.PacketParser.adcValue_S.
getSensorDataByCoord()
static byte com.nordicsemi.venusAlpha01a.PacketParser.getSensorDataByCoord (int nRowIndex, int nColIndex) static
Definition at line 45 of file PacketParser.java.
Referenced by com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
isPacketCompleted()
static boolean com.nordicsemi.venusAlpha01a.PacketParser.isPacketCompleted () static
Definition at line 245 of file PacketParser.java.
References com.nordicsemi.venusAlpha01a.PacketParser.m_isPacketCompleted.
Referenced by com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
isPostureValid_Row1()
static boolean com.nordicsemi.venusAlpha01a.PacketParser.isPostureValid_Row1 () static
Definition at line 149 of file PacketParser.java.
References com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW1.
Referenced by com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
ParseOnePacket()
void com.nordicsemi.venusAlpha01a.PacketParser.ParseOnePacket (byte [] packet_raw_data)
전달 받은 압력 값을 구분하고 해당 값들을 변수에 Setting
Parameters
Definition at line 67 of file PacketParser.java.
Referenced by com.mdex.venusAlpha01a.MainActivity.onClick_Save().
Member Data Documentation
adcValue_M
final byte [] com.nordicsemi.venusAlpha01a.PacketParser.adcValue_M = new byte[20] static
Definition at line 33 of file PacketParser.java.
Referenced by com.nordicsemi.venusAlpha01a.PacketParser.getDataMainBoard().
adcValue_S
final byte [] com.nordicsemi.venusAlpha01a.PacketParser.adcValue_S = new byte[20] static
Definition at line 34 of file PacketParser.java.
Referenced by com.nordicsemi.venusAlpha01a.PacketParser.getDataShieldBoard().
def_CELL_COUNT_ROW0
byte com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW0 = 6 static
Definition at line 23 of file PacketParser.java.
Referenced by com.mdex.venusAlpha01a.MainActivity.onBackPressed(), and com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
def_CELL_COUNT_ROW1
byte com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW1 = 15 static
Definition at line 24 of file PacketParser.java.
Referenced by com.nordicsemi.venusAlpha01a.PacketParser.getCOC_left_Row1(), com.nordicsemi.venusAlpha01a.PacketParser.getCOM_x_Row1(), com.nordicsemi.venusAlpha01a.PacketParser.isPostureValid_Row1(), com.mdex.venusAlpha01a.MainActivity.onBackPressed(), and com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
def_CELL_COUNT_ROW2
byte com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW2 = 10 static
Definition at line 25 of file PacketParser.java.
Referenced by com.mdex.venusAlpha01a.MainActivity.onBackPressed(), and com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
m_BatteryLevel
byte com.nordicsemi.venusAlpha01a.PacketParser.m_BatteryLevel = 0 static
Definition at line 22 of file PacketParser.java.
Referenced by com.nordicsemi.venusAlpha01a.PacketParser.getBatteryLevel().
m_isPacketCompleted
boolean com.nordicsemi.venusAlpha01a.PacketParser.m_isPacketCompleted = false static
Definition at line 36 of file PacketParser.java.
Referenced by com.nordicsemi.venusAlpha01a.PacketParser.isPacketCompleted().
nChairVal_Row0
byte [] com.nordicsemi.venusAlpha01a.PacketParser.nChairVal_Row0 = new byte [def_CELL_COUNT_ROW0] static
Definition at line 27 of file PacketParser.java.
nChairVal_Row1
byte [] com.nordicsemi.venusAlpha01a.PacketParser.nChairVal_Row1 = new byte [def_CELL_COUNT_ROW1] static
Definition at line 28 of file PacketParser.java.
nChairVal_Row2
byte [] com.nordicsemi.venusAlpha01a.PacketParser.nChairVal_Row2 = new byte [def_CELL_COUNT_ROW2] static
Definition at line 29 of file PacketParser.java.
textHexaMain
String com.nordicsemi.venusAlpha01a.PacketParser.textHexaMain = " " static
Definition at line 38 of file PacketParser.java.
Referenced by com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
textHexaShield
String com.nordicsemi.venusAlpha01a.PacketParser.textHexaShield = " " static
Definition at line 39 of file PacketParser.java.
Referenced by com.mdex.venusAlpha01a.MainActivity.onRadioClicked().
The documentation for this class was generated from the following file:
app/src/main/java/com/nordicsemi/venusAlpha01a/PacketParser.java