SCMS_VENUS: com.mdex.venusAlpha01a.MainActivity Class Reference
com.mdex.venusAlpha01a.MainActivity Class Reference
this is main function for run this app
Classes
enum POSTURE_tag
Public Member Functions
void onCreate (Bundle savedInstanceState)
void onClick_Save (View v)
To Save Sitting Data, Make CSV File.
void onStart ()
void onDestroy ()
진행중인 서비스 STOP
void onResume ()
void onConfigurationChanged (Configuration newConfig)
void onActivityResult (int requestCode, int resultCode, Intent data)
requestCode에 따른 결과 값 도출
void onCheckedChanged (RadioGroup group, int checkedId)
void onBackPressed ()
Static Public Attributes
static final String TAG = "nRFUART"
Protected Member Functions
void onStop ()
void onPause ()
void onRestart ()
void onRadioClicked (View view)
Detailed Description
this is main function for run this app
show values of sence and save to CSV File
Author
Marveldex
Date
2017-03-17
Version
0.0.1
list1
list2
Definition at line 118 of file MainActivity.java.
Member Function Documentation
onActivityResult()
void com.mdex.venusAlpha01a.MainActivity.onActivityResult (int requestCode, int resultCode, Intent data)
requestCode에 따른 결과 값 도출
REQUEST_SELECT_DEVICE - DeviceListActivity에서 선택된 device의 주소 넘겨 받아 device Connection을 한다.
Parameters
requestCode,int resultCode, Intent data
Returns
Exceptions
Definition at line 567 of file MainActivity.java.
References com.mdex.venusAlpha01a.UartService.connect().
onBackPressed()
void com.mdex.venusAlpha01a.MainActivity.onBackPressed ()
Parameters
Definition at line 619 of file MainActivity.java.
References com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW0, com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW1, and com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW2.
onCheckedChanged()
void com.mdex.venusAlpha01a.MainActivity.onCheckedChanged (RadioGroup group, int checkedId)
Definition at line 602 of file MainActivity.java.
onClick_Save()
void com.mdex.venusAlpha01a.MainActivity.onClick_Save (View v)
To Save Sitting Data, Make CSV File.
IF you Click the Button, Check the Button String. if the String is'Start Save' then this App Start saving Date and when you click the Button again, Make CSV File
Parameters
Definition at line 278 of file MainActivity.java.
References com.mdex.venusAlpha01a.UartService.ACTION_DATA_AVAILABLE, com.mdex.venusAlpha01a.UartService.ACTION_GATT_CONNECTED, com.mdex.venusAlpha01a.UartService.ACTION_GATT_DISCONNECTED, com.mdex.venusAlpha01a.UartService.ACTION_GATT_SERVICES_DISCOVERED, com.mdex.venusAlpha01a.UartService.close(), com.mdex.venusAlpha01a.UartService.DEVICE_DOES_NOT_SUPPORT_UART, com.mdex.venusAlpha01a.UartService.disconnect(), com.mdex.venusAlpha01a.UartService.enableTXNotification(), com.mdex.venusAlpha01a.UartService.EXTRA_DATA, and com.nordicsemi.venusAlpha01a.PacketParser.ParseOnePacket().
onConfigurationChanged()
void com.mdex.venusAlpha01a.MainActivity.onConfigurationChanged (Configuration newConfig)
Definition at line 554 of file MainActivity.java.
onCreate()
void com.mdex.venusAlpha01a.MainActivity.onCreate (Bundle savedInstanceState)
Disconnect Ble with Venus Board
if you click this Button, Ble Connection is Stopped
Parameters
Definition at line 150 of file MainActivity.java.
References com.mdex.venusAlpha01a.UartService.disconnect(), com.mdex.venusAlpha01a.UartService.initialize(), and com.mdex.venusAlpha01a.UartService.writeRXCharacteristic().
onDestroy()
void com.mdex.venusAlpha01a.MainActivity.onDestroy ()
진행중인 서비스 STOP
Parameters
Definition at line 508 of file MainActivity.java.
onPause()
void com.mdex.venusAlpha01a.MainActivity.onPause () protected
Definition at line 530 of file MainActivity.java.
onRadioClicked()
void com.mdex.venusAlpha01a.MainActivity.onRadioClicked (View view) protected
Definition at line 689 of file MainActivity.java.
References com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW0, com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW1, com.nordicsemi.venusAlpha01a.PacketParser.def_CELL_COUNT_ROW2, com.nordicsemi.venusAlpha01a.PacketParser.getBatteryLevel(), com.nordicsemi.venusAlpha01a.PacketParser.getCOC_left_Row1(), com.nordicsemi.venusAlpha01a.PacketParser.getCOC_right_Row1(), com.nordicsemi.venusAlpha01a.PacketParser.getCOM_x_Row1(), com.nordicsemi.venusAlpha01a.PacketParser.getSensorDataByCoord(), com.nordicsemi.venusAlpha01a.PacketParser.isPacketCompleted(), com.nordicsemi.venusAlpha01a.PacketParser.isPostureValid_Row1(), com.nordicsemi.venusAlpha01a.PacketParser.textHexaMain, and com.nordicsemi.venusAlpha01a.PacketParser.textHexaShield.
onRestart()
void com.mdex.venusAlpha01a.MainActivity.onRestart () protected
Definition at line 536 of file MainActivity.java.
onResume()
void com.mdex.venusAlpha01a.MainActivity.onResume ()
Definition at line 542 of file MainActivity.java.
onStart()
void com.mdex.venusAlpha01a.MainActivity.onStart ()
Definition at line 494 of file MainActivity.java.
onStop()
void com.mdex.venusAlpha01a.MainActivity.onStop () protected
Definition at line 524 of file MainActivity.java.
Member Data Documentation
TAG
final String com.mdex.venusAlpha01a.MainActivity.TAG = "nRFUART" static
Definition at line 122 of file MainActivity.java.
The documentation for this class was generated from the following file:
app/src/main/java/com/nordicsemi/venusAlpha01a/MainActivity.java